apiVersion: v1
kind: Secret
metadata:
  name: github-access
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: /root/.ssh/id_rsa
  known_hosts:  /root/.ssh/known_hosts
