apiVersion: v1
kind: Secret
metadata:
  name: ebeaudoi-quayrobot1-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaV0psWVhWa2Iya3JjWFZoZVhKdlltOTBNVG80VmtGU1dVTk5VekpZVERWT1MxWlZORFZQUlRGWFQxcEdRVmRETjBWQk5VZE5UVkZEUWpoTU1Fa3hSRkpSU2xoRVZGZEVWRXRUV1ZFM1VETkdOVEpOIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
