apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: task-scc
allowedCapabilities:
  - SETFCAP
fsGroup:
  type: MustRunAs
runAsUser: 
  type: RunAsAny
seLinuxContext: 
  type: RunAsAny
