apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-pod-task
spec:
  params:
  - name: app-name
    type: string
    description: The application name
  steps:
  - name: create-pod
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli
    imagePullPolicy: IfNotPresent
    script: |
      cat << EOF | oc apply -f -
      apiVersion: v1
      kind: Pod
      metadata:
        name: pipeline-pod
      spec:
        restartPolicy: Never
        containers:
        - name: pipeline-container
          image: quay.io/ebeaudoi/pipeline:latest
      EOF
